/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as ContactsRouteRouteImport } from './routes/contacts/route'
import { Route as DownloadsRouteRouteImport } from './routes/downloads/route'
import { Route as KbRouteRouteImport } from './routes/kb/route'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignOutRouteImport } from './routes/(auth)/sign-out'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as protectedAdminRouteRouteImport } from './routes/(protected)/admin/route'
import { Route as protectedArticlesRouteRouteImport } from './routes/(protected)/articles/route'
import { Route as protectedCategoriesRouteImport } from './routes/(protected)/categories'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as protectedDocumentsRouteRouteImport } from './routes/(protected)/documents/route'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as KbIndexRouteImport } from './routes/kb/index'
import { Route as KbCategorySlugRouteImport } from './routes/kb/$categorySlug'
import { Route as UploadsKeyRouteImport } from './routes/uploads/$key'
import { Route as protectedAdminIndexRouteImport } from './routes/(protected)/admin/index'
import { Route as protectedAdminCategoriesRouteImport } from './routes/(protected)/admin/categories'
import { Route as protectedArticlesIndexRouteImport } from './routes/(protected)/articles/index'
import { Route as protectedArticlesNewRouteImport } from './routes/(protected)/articles/new'
import { Route as protectedContactsManageRouteImport } from './routes/(protected)/contacts/manage'
import { Route as protectedDocumentsIndexRouteImport } from './routes/(protected)/documents/index'
import { Route as protectedDocumentsNewRouteImport } from './routes/(protected)/documents/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as KbCategorySlugArticleSlugRouteImport } from './routes/kb/$categorySlug/$articleSlug'
import { Route as UploadsDocumentsKeyRouteImport } from './routes/uploads/documents/$key'
import { Route as protectedArticlesArticleIdEditRouteImport } from './routes/(protected)/articles/$articleId/edit'
import { Route as protectedDocumentsDocumentIdEditRouteImport } from './routes/(protected)/documents/$documentId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRouteRoute = ContactsRouteRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRouteRoute = DownloadsRouteRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const KbRouteRoute = KbRouteRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignOutRoute = authSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedAdminRouteRoute = protectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedArticlesRouteRoute = protectedArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedCategoriesRoute = protectedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDocumentsRouteRoute = protectedDocumentsRouteRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => protectedRouteRoute,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactsRouteRoute,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DownloadsRouteRoute,
} as any)
const KbIndexRoute = KbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KbRouteRoute,
} as any)
const KbCategorySlugRoute = KbCategorySlugRouteImport.update({
  id: '/$categorySlug',
  path: '/$categorySlug',
  getParentRoute: () => KbRouteRoute,
} as any)
const UploadsKeyRoute = UploadsKeyRouteImport.update({
  id: '/uploads/$key',
  path: '/uploads/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAdminIndexRoute = protectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)
const protectedAdminCategoriesRoute =
  protectedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => protectedAdminRouteRoute,
  } as any)
const protectedArticlesIndexRoute = protectedArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedArticlesRouteRoute,
} as any)
const protectedArticlesNewRoute = protectedArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => protectedArticlesRouteRoute,
} as any)
const protectedContactsManageRoute = protectedContactsManageRouteImport.update({
  id: '/contacts/manage',
  path: '/contacts/manage',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDocumentsIndexRoute = protectedDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedDocumentsRouteRoute,
} as any)
const protectedDocumentsNewRoute = protectedDocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => protectedDocumentsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const KbCategorySlugArticleSlugRoute =
  KbCategorySlugArticleSlugRouteImport.update({
    id: '/$articleSlug',
    path: '/$articleSlug',
    getParentRoute: () => KbCategorySlugRoute,
  } as any)
const UploadsDocumentsKeyRoute = UploadsDocumentsKeyRouteImport.update({
  id: '/uploads/documents/$key',
  path: '/uploads/documents/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedArticlesArticleIdEditRoute =
  protectedArticlesArticleIdEditRouteImport.update({
    id: '/$articleId/edit',
    path: '/$articleId/edit',
    getParentRoute: () => protectedArticlesRouteRoute,
  } as any)
const protectedDocumentsDocumentIdEditRoute =
  protectedDocumentsDocumentIdEditRouteImport.update({
    id: '/$documentId/edit',
    path: '/$documentId/edit',
    getParentRoute: () => protectedDocumentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRouteRouteWithChildren
  '/downloads': typeof DownloadsRouteRouteWithChildren
  '/kb': typeof KbRouteRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/admin': typeof protectedAdminRouteRouteWithChildren
  '/articles': typeof protectedArticlesRouteRouteWithChildren
  '/documents': typeof protectedDocumentsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-out': typeof authSignOutRoute
  '/sign-up': typeof authSignUpRoute
  '/categories': typeof protectedCategoriesRoute
  '/dashboard': typeof protectedDashboardRoute
  '/kb/$categorySlug': typeof KbCategorySlugRouteWithChildren
  '/uploads/$key': typeof UploadsKeyRoute
  '/contacts/': typeof ContactsIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/kb/': typeof KbIndexRoute
  '/admin/categories': typeof protectedAdminCategoriesRoute
  '/articles/new': typeof protectedArticlesNewRoute
  '/contacts/manage': typeof protectedContactsManageRoute
  '/documents/new': typeof protectedDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kb/$categorySlug/$articleSlug': typeof KbCategorySlugArticleSlugRoute
  '/uploads/documents/$key': typeof UploadsDocumentsKeyRoute
  '/admin/': typeof protectedAdminIndexRoute
  '/articles/': typeof protectedArticlesIndexRoute
  '/documents/': typeof protectedDocumentsIndexRoute
  '/articles/$articleId/edit': typeof protectedArticlesArticleIdEditRoute
  '/documents/$documentId/edit': typeof protectedDocumentsDocumentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/sign-in': typeof authSignInRoute
  '/sign-out': typeof authSignOutRoute
  '/sign-up': typeof authSignUpRoute
  '/categories': typeof protectedCategoriesRoute
  '/dashboard': typeof protectedDashboardRoute
  '/kb/$categorySlug': typeof KbCategorySlugRouteWithChildren
  '/uploads/$key': typeof UploadsKeyRoute
  '/contacts': typeof ContactsIndexRoute
  '/downloads': typeof DownloadsIndexRoute
  '/kb': typeof KbIndexRoute
  '/admin/categories': typeof protectedAdminCategoriesRoute
  '/articles/new': typeof protectedArticlesNewRoute
  '/contacts/manage': typeof protectedContactsManageRoute
  '/documents/new': typeof protectedDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kb/$categorySlug/$articleSlug': typeof KbCategorySlugArticleSlugRoute
  '/uploads/documents/$key': typeof UploadsDocumentsKeyRoute
  '/admin': typeof protectedAdminIndexRoute
  '/articles': typeof protectedArticlesIndexRoute
  '/documents': typeof protectedDocumentsIndexRoute
  '/articles/$articleId/edit': typeof protectedArticlesArticleIdEditRoute
  '/documents/$documentId/edit': typeof protectedDocumentsDocumentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/contacts': typeof ContactsRouteRouteWithChildren
  '/downloads': typeof DownloadsRouteRouteWithChildren
  '/kb': typeof KbRouteRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/(protected)/admin': typeof protectedAdminRouteRouteWithChildren
  '/(protected)/articles': typeof protectedArticlesRouteRouteWithChildren
  '/(protected)/documents': typeof protectedDocumentsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-out': typeof authSignOutRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(protected)/categories': typeof protectedCategoriesRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/kb/$categorySlug': typeof KbCategorySlugRouteWithChildren
  '/uploads/$key': typeof UploadsKeyRoute
  '/contacts/': typeof ContactsIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/kb/': typeof KbIndexRoute
  '/(protected)/admin/categories': typeof protectedAdminCategoriesRoute
  '/(protected)/articles/new': typeof protectedArticlesNewRoute
  '/(protected)/contacts/manage': typeof protectedContactsManageRoute
  '/(protected)/documents/new': typeof protectedDocumentsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kb/$categorySlug/$articleSlug': typeof KbCategorySlugArticleSlugRoute
  '/uploads/documents/$key': typeof UploadsDocumentsKeyRoute
  '/(protected)/admin/': typeof protectedAdminIndexRoute
  '/(protected)/articles/': typeof protectedArticlesIndexRoute
  '/(protected)/documents/': typeof protectedDocumentsIndexRoute
  '/(protected)/articles/$articleId/edit': typeof protectedArticlesArticleIdEditRoute
  '/(protected)/documents/$documentId/edit': typeof protectedDocumentsDocumentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/downloads'
    | '/kb'
    | '/pending-approval'
    | '/admin'
    | '/articles'
    | '/documents'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/categories'
    | '/dashboard'
    | '/kb/$categorySlug'
    | '/uploads/$key'
    | '/contacts/'
    | '/downloads/'
    | '/kb/'
    | '/admin/categories'
    | '/articles/new'
    | '/contacts/manage'
    | '/documents/new'
    | '/api/auth/$'
    | '/kb/$categorySlug/$articleSlug'
    | '/uploads/documents/$key'
    | '/admin/'
    | '/articles/'
    | '/documents/'
    | '/articles/$articleId/edit'
    | '/documents/$documentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pending-approval'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/categories'
    | '/dashboard'
    | '/kb/$categorySlug'
    | '/uploads/$key'
    | '/contacts'
    | '/downloads'
    | '/kb'
    | '/admin/categories'
    | '/articles/new'
    | '/contacts/manage'
    | '/documents/new'
    | '/api/auth/$'
    | '/kb/$categorySlug/$articleSlug'
    | '/uploads/documents/$key'
    | '/admin'
    | '/articles'
    | '/documents'
    | '/articles/$articleId/edit'
    | '/documents/$documentId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/contacts'
    | '/downloads'
    | '/kb'
    | '/pending-approval'
    | '/(protected)/admin'
    | '/(protected)/articles'
    | '/(protected)/documents'
    | '/(auth)/sign-in'
    | '/(auth)/sign-out'
    | '/(auth)/sign-up'
    | '/(protected)/categories'
    | '/(protected)/dashboard'
    | '/kb/$categorySlug'
    | '/uploads/$key'
    | '/contacts/'
    | '/downloads/'
    | '/kb/'
    | '/(protected)/admin/categories'
    | '/(protected)/articles/new'
    | '/(protected)/contacts/manage'
    | '/(protected)/documents/new'
    | '/api/auth/$'
    | '/kb/$categorySlug/$articleSlug'
    | '/uploads/documents/$key'
    | '/(protected)/admin/'
    | '/(protected)/articles/'
    | '/(protected)/documents/'
    | '/(protected)/articles/$articleId/edit'
    | '/(protected)/documents/$documentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  ContactsRouteRoute: typeof ContactsRouteRouteWithChildren
  DownloadsRouteRoute: typeof DownloadsRouteRouteWithChildren
  KbRouteRoute: typeof KbRouteRouteWithChildren
  PendingApprovalRoute: typeof PendingApprovalRoute
  UploadsKeyRoute: typeof UploadsKeyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  UploadsDocumentsKeyRoute: typeof UploadsDocumentsKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb': {
      id: '/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof KbRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-out': {
      id: '/(auth)/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof authSignOutRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/admin': {
      id: '/(protected)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof protectedAdminRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/articles': {
      id: '/(protected)/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof protectedArticlesRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/categories': {
      id: '/(protected)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof protectedCategoriesRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/documents': {
      id: '/(protected)/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof protectedDocumentsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof ContactsRouteRoute
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/'
      fullPath: '/downloads/'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof DownloadsRouteRoute
    }
    '/kb/': {
      id: '/kb/'
      path: '/'
      fullPath: '/kb/'
      preLoaderRoute: typeof KbIndexRouteImport
      parentRoute: typeof KbRouteRoute
    }
    '/kb/$categorySlug': {
      id: '/kb/$categorySlug'
      path: '/$categorySlug'
      fullPath: '/kb/$categorySlug'
      preLoaderRoute: typeof KbCategorySlugRouteImport
      parentRoute: typeof KbRouteRoute
    }
    '/uploads/$key': {
      id: '/uploads/$key'
      path: '/uploads/$key'
      fullPath: '/uploads/$key'
      preLoaderRoute: typeof UploadsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/admin/': {
      id: '/(protected)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof protectedAdminIndexRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/admin/categories': {
      id: '/(protected)/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof protectedAdminCategoriesRouteImport
      parentRoute: typeof protectedAdminRouteRoute
    }
    '/(protected)/articles/': {
      id: '/(protected)/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof protectedArticlesIndexRouteImport
      parentRoute: typeof protectedArticlesRouteRoute
    }
    '/(protected)/articles/new': {
      id: '/(protected)/articles/new'
      path: '/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof protectedArticlesNewRouteImport
      parentRoute: typeof protectedArticlesRouteRoute
    }
    '/(protected)/contacts/manage': {
      id: '/(protected)/contacts/manage'
      path: '/contacts/manage'
      fullPath: '/contacts/manage'
      preLoaderRoute: typeof protectedContactsManageRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/documents/': {
      id: '/(protected)/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof protectedDocumentsIndexRouteImport
      parentRoute: typeof protectedDocumentsRouteRoute
    }
    '/(protected)/documents/new': {
      id: '/(protected)/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof protectedDocumentsNewRouteImport
      parentRoute: typeof protectedDocumentsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/$categorySlug/$articleSlug': {
      id: '/kb/$categorySlug/$articleSlug'
      path: '/$articleSlug'
      fullPath: '/kb/$categorySlug/$articleSlug'
      preLoaderRoute: typeof KbCategorySlugArticleSlugRouteImport
      parentRoute: typeof KbCategorySlugRoute
    }
    '/uploads/documents/$key': {
      id: '/uploads/documents/$key'
      path: '/uploads/documents/$key'
      fullPath: '/uploads/documents/$key'
      preLoaderRoute: typeof UploadsDocumentsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/articles/$articleId/edit': {
      id: '/(protected)/articles/$articleId/edit'
      path: '/$articleId/edit'
      fullPath: '/articles/$articleId/edit'
      preLoaderRoute: typeof protectedArticlesArticleIdEditRouteImport
      parentRoute: typeof protectedArticlesRouteRoute
    }
    '/(protected)/documents/$documentId/edit': {
      id: '/(protected)/documents/$documentId/edit'
      path: '/$documentId/edit'
      fullPath: '/documents/$documentId/edit'
      preLoaderRoute: typeof protectedDocumentsDocumentIdEditRouteImport
      parentRoute: typeof protectedDocumentsRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignOutRoute: typeof authSignOutRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignOutRoute: authSignOutRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedAdminRouteRouteChildren {
  protectedAdminCategoriesRoute: typeof protectedAdminCategoriesRoute
  protectedAdminIndexRoute: typeof protectedAdminIndexRoute
}

const protectedAdminRouteRouteChildren: protectedAdminRouteRouteChildren = {
  protectedAdminCategoriesRoute: protectedAdminCategoriesRoute,
  protectedAdminIndexRoute: protectedAdminIndexRoute,
}

const protectedAdminRouteRouteWithChildren =
  protectedAdminRouteRoute._addFileChildren(protectedAdminRouteRouteChildren)

interface protectedArticlesRouteRouteChildren {
  protectedArticlesNewRoute: typeof protectedArticlesNewRoute
  protectedArticlesIndexRoute: typeof protectedArticlesIndexRoute
  protectedArticlesArticleIdEditRoute: typeof protectedArticlesArticleIdEditRoute
}

const protectedArticlesRouteRouteChildren: protectedArticlesRouteRouteChildren =
  {
    protectedArticlesNewRoute: protectedArticlesNewRoute,
    protectedArticlesIndexRoute: protectedArticlesIndexRoute,
    protectedArticlesArticleIdEditRoute: protectedArticlesArticleIdEditRoute,
  }

const protectedArticlesRouteRouteWithChildren =
  protectedArticlesRouteRoute._addFileChildren(
    protectedArticlesRouteRouteChildren,
  )

interface protectedDocumentsRouteRouteChildren {
  protectedDocumentsNewRoute: typeof protectedDocumentsNewRoute
  protectedDocumentsIndexRoute: typeof protectedDocumentsIndexRoute
  protectedDocumentsDocumentIdEditRoute: typeof protectedDocumentsDocumentIdEditRoute
}

const protectedDocumentsRouteRouteChildren: protectedDocumentsRouteRouteChildren =
  {
    protectedDocumentsNewRoute: protectedDocumentsNewRoute,
    protectedDocumentsIndexRoute: protectedDocumentsIndexRoute,
    protectedDocumentsDocumentIdEditRoute:
      protectedDocumentsDocumentIdEditRoute,
  }

const protectedDocumentsRouteRouteWithChildren =
  protectedDocumentsRouteRoute._addFileChildren(
    protectedDocumentsRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedAdminRouteRoute: typeof protectedAdminRouteRouteWithChildren
  protectedArticlesRouteRoute: typeof protectedArticlesRouteRouteWithChildren
  protectedDocumentsRouteRoute: typeof protectedDocumentsRouteRouteWithChildren
  protectedCategoriesRoute: typeof protectedCategoriesRoute
  protectedDashboardRoute: typeof protectedDashboardRoute
  protectedContactsManageRoute: typeof protectedContactsManageRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedAdminRouteRoute: protectedAdminRouteRouteWithChildren,
  protectedArticlesRouteRoute: protectedArticlesRouteRouteWithChildren,
  protectedDocumentsRouteRoute: protectedDocumentsRouteRouteWithChildren,
  protectedCategoriesRoute: protectedCategoriesRoute,
  protectedDashboardRoute: protectedDashboardRoute,
  protectedContactsManageRoute: protectedContactsManageRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface ContactsRouteRouteChildren {
  ContactsIndexRoute: typeof ContactsIndexRoute
}

const ContactsRouteRouteChildren: ContactsRouteRouteChildren = {
  ContactsIndexRoute: ContactsIndexRoute,
}

const ContactsRouteRouteWithChildren = ContactsRouteRoute._addFileChildren(
  ContactsRouteRouteChildren,
)

interface DownloadsRouteRouteChildren {
  DownloadsIndexRoute: typeof DownloadsIndexRoute
}

const DownloadsRouteRouteChildren: DownloadsRouteRouteChildren = {
  DownloadsIndexRoute: DownloadsIndexRoute,
}

const DownloadsRouteRouteWithChildren = DownloadsRouteRoute._addFileChildren(
  DownloadsRouteRouteChildren,
)

interface KbCategorySlugRouteChildren {
  KbCategorySlugArticleSlugRoute: typeof KbCategorySlugArticleSlugRoute
}

const KbCategorySlugRouteChildren: KbCategorySlugRouteChildren = {
  KbCategorySlugArticleSlugRoute: KbCategorySlugArticleSlugRoute,
}

const KbCategorySlugRouteWithChildren = KbCategorySlugRoute._addFileChildren(
  KbCategorySlugRouteChildren,
)

interface KbRouteRouteChildren {
  KbCategorySlugRoute: typeof KbCategorySlugRouteWithChildren
  KbIndexRoute: typeof KbIndexRoute
}

const KbRouteRouteChildren: KbRouteRouteChildren = {
  KbCategorySlugRoute: KbCategorySlugRouteWithChildren,
  KbIndexRoute: KbIndexRoute,
}

const KbRouteRouteWithChildren =
  KbRouteRoute._addFileChildren(KbRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  ContactsRouteRoute: ContactsRouteRouteWithChildren,
  DownloadsRouteRoute: DownloadsRouteRouteWithChildren,
  KbRouteRoute: KbRouteRouteWithChildren,
  PendingApprovalRoute: PendingApprovalRoute,
  UploadsKeyRoute: UploadsKeyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  UploadsDocumentsKeyRoute: UploadsDocumentsKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
